#include "ATIVIDADE_02.h"


int ATIVIDADE_02_TESTES(void){

    
    int resultado = 0;

    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 01 - IGUALDADE                    :: 01",ATIVIDADE_02_01_TESTE_IGUALDADE_TESTE_1());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 01 - IGUALDADE                    :: 02",ATIVIDADE_02_01_TESTE_IGUALDADE_TESTE_2());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 01 - IGUALDADE                    :: 03",ATIVIDADE_02_01_TESTE_IGUALDADE_TESTE_3());

    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 02 - MAIOR                        :: 01",ATIVIDADE_02_02_TESTE_MAIOR_TESTE_1());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 02 - MAIOR                        :: 02",ATIVIDADE_02_02_TESTE_MAIOR_TESTE_2());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 02 - MAIOR                        :: 03",ATIVIDADE_02_02_TESTE_MAIOR_TESTE_3());

    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 03 - DELTA                        :: 01",ATIVIDADE_02_03_TESTE_DELTA_TESTE_1());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 03 - DELTA                        :: 02",ATIVIDADE_02_03_TESTE_DELTA_TESTE_2());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 03 - DELTA                        :: 03",ATIVIDADE_02_03_TESTE_DELTA_TESTE_3());

    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 03 - RAIZ 1                       :: 01",ATIVIDADE_02_03_TESTE_RAIZ_1_TESTE_1());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 03 - RAIZ 1                       :: 02",ATIVIDADE_02_03_TESTE_RAIZ_1_TESTE_2());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 03 - RAIZ 1                       :: 03",ATIVIDADE_02_03_TESTE_RAIZ_1_TESTE_3());

    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 03 - RAIZ 2                       :: 01",ATIVIDADE_02_03_TESTE_RAIZ_2_TESTE_1());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 03 - RAIZ 2                       :: 02",ATIVIDADE_02_03_TESTE_RAIZ_2_TESTE_2());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 03 - RAIZ 2                       :: 03",ATIVIDADE_02_03_TESTE_RAIZ_2_TESTE_3());

    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO DENTRO              :: 01",ATIVIDADE_02_04_TESTE_DENTRO_TESTE_1());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO DENTRO              :: 02",ATIVIDADE_02_04_TESTE_DENTRO_TESTE_2());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO DENTRO              :: 03",ATIVIDADE_02_04_TESTE_DENTRO_TESTE_3());

    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO X FORA              :: 01",ATIVIDADE_02_04_TESTE_X_FORA_TESTE_1());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO X FORA              :: 02",ATIVIDADE_02_04_TESTE_X_FORA_TESTE_2());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO X FORA              :: 03",ATIVIDADE_02_04_TESTE_X_FORA_TESTE_3());

    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO Y FORA              :: 01",ATIVIDADE_02_04_TESTE_Y_FORA_TESTE_1());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO Y FORA              :: 02",ATIVIDADE_02_04_TESTE_Y_FORA_TESTE_2());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO Y FORA              :: 03",ATIVIDADE_02_04_TESTE_Y_FORA_TESTE_3());

    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO X LINHA             :: 01",ATIVIDADE_02_04_TESTE_X_LINHA_TESTE_1());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO X LINHA             :: 02",ATIVIDADE_02_04_TESTE_X_LINHA_TESTE_2());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO X LINHA             :: 03",ATIVIDADE_02_04_TESTE_X_LINHA_TESTE_3());
    
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO Y LINHA             :: 01",ATIVIDADE_02_04_TESTE_Y_LINHA_TESTE_1());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO Y LINHA             :: 02",ATIVIDADE_02_04_TESTE_Y_LINHA_TESTE_2());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 04 - QUADRADO Y LINHA             :: 03",ATIVIDADE_02_04_TESTE_Y_LINHA_TESTE_3());
   
   
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 05 - POLUIÇÃO                     :: 01",ATIVIDADE_02_05_TESTE_POLUICAO_TESTE_1());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 05 - POLUIÇÃO                     :: 02",ATIVIDADE_02_05_TESTE_POLUICAO_TESTE_2());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 05 - POLUIÇÃO                     :: 03",ATIVIDADE_02_05_TESTE_POLUICAO_TESTE_3());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 05 - POLUIÇÃO                     :: 04",ATIVIDADE_02_05_TESTE_POLUICAO_TESTE_4());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 05 - POLUIÇÃO                     :: 05",ATIVIDADE_02_05_TESTE_POLUICAO_TESTE_5());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 05 - POLUIÇÃO                     :: 06",ATIVIDADE_02_05_TESTE_POLUICAO_TESTE_6());

    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 06 - TRIÂNGULO                    :: 01",ATIVIDADE_02_06_TESTE_TRIANGULO_TESTE_1());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 06 - TRIÂNGULO                    :: 02",ATIVIDADE_02_06_TESTE_TRIANGULO_TESTE_2());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 06 - TRIÂNGULO                    :: 03",ATIVIDADE_02_06_TESTE_TRIANGULO_TESTE_3());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 06 - TRIÂNGULO                    :: 04",ATIVIDADE_02_06_TESTE_TRIANGULO_TESTE_4());
    resultado+=VALIDAR("LISTA 02 :: ATIVIDADE 06 - TRIÂNGULO                    :: 05",ATIVIDADE_02_06_TESTE_TRIANGULO_TESTE_5());

    
    return resultado;
}