
#include <stdio.h>
#include "../TESTE/TESTE.h"

int ATIVIDADE_03_03 (void);

int ATIVIDADE_03_03_TESTE_MEDIA_DE_IDADES_TESTE_1(void);
int ATIVIDADE_03_03_TESTE_MEDIA_DE_IDADES_TESTE_2(void);
int ATIVIDADE_03_03_TESTE_MEDIA_DE_IDADES_TESTE_3(void);
