
#include <stdio.h>

float cilindro_volume(float raio,float altura);
int ATIVIDADE_01_03(void);
int ATIVIDADE_01_03_TESTE_CALCULAR_CILINDO_VOLUME_01();
int ATIVIDADE_01_03_TESTE_CALCULAR_CILINDO_VOLUME_02();
int ATIVIDADE_01_03_TESTE_CALCULAR_CILINDO_VOLUME_03();