#include "ATIVIDADE_01.h"


int ATIVIDADE_01_TESTES(void){

    
    int resultado = 0;
    
    resultado+=VALIDAR("LISTA 01 :: ATIVIDADE 01 - TROCA DE VALORES              :: 01",ATIVIDADE_01_01_TESTE_01_TROCAR_VALOR_TESTE_01());
    resultado+=VALIDAR("LISTA 01 :: ATIVIDADE 01 - TROCA DE VALORES              :: 02",ATIVIDADE_01_01_TESTE_01_TROCAR_VALOR_TESTE_02());
    resultado+=VALIDAR("LISTA 01 :: ATIVIDADE 01 - TROCA DE VALORES              :: 03",ATIVIDADE_01_01_TESTE_01_TROCAR_VALOR_TESTE_03());

    resultado+=VALIDAR("LISTA 01 :: ATIVIDADE 02 - CALCULAR MÉDIA                :: 01",ATIVIDADE_01_02_TESTE_CALCULAR_MEDIA_01());
    resultado+=VALIDAR("LISTA 01 :: ATIVIDADE 02 - CALCULAR MÉDIA                :: 02",ATIVIDADE_01_02_TESTE_CALCULAR_MEDIA_02());
    resultado+=VALIDAR("LISTA 01 :: ATIVIDADE 02 - CALCULAR MÉDIA                :: 03",ATIVIDADE_01_02_TESTE_CALCULAR_MEDIA_03());

    resultado+=VALIDAR("LISTA 01 :: ATIVIDADE 03 - CALCULAR VOLUME DO CILINDRO   :: 01",ATIVIDADE_01_03_TESTE_CALCULAR_CILINDO_VOLUME_01());
    resultado+=VALIDAR("LISTA 01 :: ATIVIDADE 03 - CALCULAR VOLUME DO CILINDRO   :: 02",ATIVIDADE_01_03_TESTE_CALCULAR_CILINDO_VOLUME_02());
    resultado+=VALIDAR("LISTA 01 :: ATIVIDADE 03 - CALCULAR VOLUME DO CILINDRO   :: 03",ATIVIDADE_01_03_TESTE_CALCULAR_CILINDO_VOLUME_03());


    return resultado;
}